Fix issues in sfn-wdl plugin (#12)
Addresses error metadata handling errors of this form:

parse error: Invalid numeric literal at line 1, column 10

TypeError: 'str' object does not support item assignment